In [97]:
import numpy as np
## the fuction is set to use the worse case situation, 
##if you want to use best case, put survival_case=1 or reproduction_case=1 for best case
def bobcat_P(N,P_1,survival_case=None,reproduction_case=None):
    W_S=np.zeros((16,16))
    W_S_list=[0.32]+[0.68]*15
    np.fill_diagonal(W_S, W_S_list)   #Worst case survival rate matrix
    
    B_S=np.zeros((16,16))
    B_S_list=[0.34]+[0.71]*15
    np.fill_diagonal(B_S, B_S_list)   #Best case survival rate matrix
    
    W_R=np.zeros((16,16))
    W_R_list=[0.6]*2+[1.15]*14
    np.fill_diagonal(W_R, W_R_list)   #Worst case reproduction rate matrix
    
    B_R=np.zeros((16,16))
    B_R_list=[0.63]*2+[1.2]*14
    np.fill_diagonal(B_R, B_R_list)   #Worst case reproduction rate matrix
    
    sum_population=np.zeros(N)
    P_matrix=P_1
    
    
    if survival_case==1:   ##set cases
        S=B_S
    else:
        S=W_S
    if reproduction_case==1:
        R=B_R
    else:
        R=W_R
        
        
    for t in np.arange(N):
        if t==0:
            sum_population[t]=np.sum(P_1)
        else:
            if t ==1:
                survivaled_P=np.dot(S,P_1)
            else:
                survivaled_P=np.dot(S,new_population)
            reproducted_P=np.dot(R,survivaled_P)
            new_survivaled_P=survivaled_P
            for i in np.arange(len(survivaled_P))[::-1]:
                if i!=0:
                    new_survivaled_P[i]=survivaled_P[i-1]
                else:
                    new_survivaled_P[i]=0       
            new_survivaled_P[0]=np.sum(reproducted_P)
            new_population=new_survivaled_P
            sum_population[t]=np.sum(new_population)
            P_matrix=np.hstack((P_matrix,new_population))
    print('total population in each year:',sum_population)
    print('population distribution by age in each year:',
          P_matrix)        
##P_1 is the initial 16 by 1 matrix represents the number of bobcats in each age group from 1 to 16, the sum of P_1 is the
## total bobcats population in that year

In [100]:
P_1=np.array([[10]*16])   # here I used a 16 by 1 matrix with 10 in each entry as the initial condition, which means we have 10 bobcats
                        ## in each age group and in total we have 160 bobcats initially.
P_1=P_1.transpose()

bobcat_P(5,P_1)

total population in each year: [160.         213.88       197.16576    178.26342272 168.3050856 ]
population distribution by age in each year: [[ 10.         115.48        97.92416     82.58772352  78.95567622]
 [ 10.           3.2         36.9536      31.3357312   26.42807153]
 [ 10.           6.8          2.176       25.128448    21.30829722]
 [ 10.           6.8          4.624        1.47968     17.08734464]
 [ 10.           6.8          4.624        3.14432      1.0061824 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624        3.14432      2.1381376 ]
 [ 10.           6.8          4.624      